apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prosody.fullname" . }}
  labels:
    {{- include "prosody.labels" . | nindent 4 }}
type: Opaque
stringData:
 {{- toYaml .Values.secretEnvs | nindent 2 }}
