apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jicofo
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
type: Opaque
stringData:
  JICOFO_AUTH_USER: "focus"
  JICOFO_AUTH_PASSWORD: {{ .Values.jicofo.xmpp.password | default (randAlphaNum 10) | quote }}
  JICOFO_COMPONENT_SECRET: {{ .Values.jicofo.xmpp.componentSecret | default (randAlphaNum 10) | quote }}
