apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
data:
  DISABLE_HTTPS: {{ .Values.web.httpsEnabled | ternary "0" "1" | quote }}
  ENABLE_HTTP_REDIRECT: {{ .Values.web.httpRedirect | ternary "1" "0" | quote }}
  JICOFO_AUTH_USER: "focus"
  XMPP_BOSH_URL_BASE: 'http://{{ include "jitsi-meet.xmpp.server" . }}:{{ index .Values.prosody.service.ports "bosh-insecure" }}'
  {{- if .Values.web.resolverIP }}
  NGINX_RESOLVER: {{ .Values.web.resolverIP }}
  {{- end }}
  {{- with .Values.web.extraEnvs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
