{{- if and .Values.jvb.service.enabled (not (or .Values.jvb.useHostPort .Values.jvb.useHostNetwork)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}
  annotations:
    {{- with .Values.jvb.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jvb.service.type }}
  {{- with .Values.jvb.service.LoadbalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.jvb.UDPPort | default 10000 }}
      protocol: UDP
      name: rtp-udp
      {{- if and .Values.jvb.nodePort (or (eq .Values.jvb.service.type "NodePort") (eq .Values.jvb.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.jvb.nodePort }}
      {{- end }}
  {{- with .Values.jvb.service.externalIPs }}
  externalIPs:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.jvb.service.externalTrafficPolicy }}
  selector:
    {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 4 }}
{{- end }}
