apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jvb
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
type: Opaque
stringData:
  JVB_AUTH_USER: {{ .Values.jvb.xmpp.user | quote }}
  JVB_AUTH_PASSWORD: {{ .Values.jvb.xmpp.password | default (randAlphaNum 10) | quote }}
